Mag + Thruster Test programs
irvinecubesat/irvine-01-sw pull request #10
Opened 2018-07-30 20:00 UTC by niwhsa9

Added code for thruster throttle up over period controlled sine wave and code for magnetorquer software PWM on I2C. 

Mag code for software controlled PWM at the request of Mr. Shah for finer mag control despite the H-bridge circuit driven PWM on the C-card. 

Header files currently missing, will add later. Thruster code should be modified for better amplitude control.

2018-08-08 13:52 UTC, mcli commented
Test programs should go into a different directory.  Can you please create a new utility directory and move these under there?

2018-08-08 13:55 UTC, mcli requested changes
Please create a new utilities directory and put these under that directory.  We want to keep test programs separate from operational programs.

2018-08-09 04:56 UTC, niwhsa9 commented
Done.

2018-09-29 05:55 UTC, mcli approved these changes

2018-09-29 05:55 UTC, merged